Update project documentation
seas-computing/sec-directory-client pull request #28
Opened 2021-08-31 20:26 UTC by jonseitz

This builds on the previous version of the `README` by providing more details about the individual components of the app, providing links to relevant external resources (including the `sec-directory-server` project) and making some recommendations about separating development and test indices.

I've also added our standard `CODE_OF_CONDUCT` document, as well as a copy of the BSD 3-clause license that we've used in the past. 

Most importantly, there are badges now.

Please let me know if you have any suggestions for other details that we should add to the README, of if there's anything here that's not totally clear. I know, the production section is definitely a little thin, but I expect we can add to that once we actually have a deployment out in the wild.

2021-09-01 17:39 UTC, natalynyu requested changes
This is looking good. I just had a few comments on the README portion.

2021-09-01 18:04 UTC, jonseitz commented on README.md
> +As we're building for specific 55" touch screen displays ([Planar PS5561T][planar]) in portrait mode, the design of the page is fixed to a 1080x1920 rectangle with scrolling disabled. To view the app
Yeah, probably doesn't hurt to mention it. Added that in 376d2bb.

2021-09-01 18:05 UTC, jonseitz commented on README.md
> +Ideally, each developer working on the project should create their own Algolia index (and corresponding API Key) to use while developing. You can use the same index for both client and server operati
Yep, probably good to repeat that often. Added in 64ce2b0

2021-09-08 17:40 UTC, chrxr approved these changes
Looks good! Thanks.

2021-09-08 20:06 UTC, merged